let statements = {
  getallitemsDetails: {
        statement: `  SELECT
            items_id,
            (SELECT AR_NAME  FROM INVENTORY.ITEMS M WHERE M.ITEMS_ID = I.ITEMS_ID) ITEM_AR_NAME,
            (SELECT EN_NAME  FROM INVENTORY.ITEMS M WHERE M.ITEMS_ID = I.ITEMS_ID) ITEM_EN_NAME,
            shippable_enabled_flag,
            purchasing_enabled_flag,
            customer_order_enabled_flag,
            internal_order_enabled_flag,
            invoiceable_item_flag,
            returnable_flag,
            inspection_required_flag,
            receipt_required_flag,
            rfq_required_flag,
            allow_substitute_receipts_flag,
            allow_unordered_receipts_flag,
            allow_express_delivery_flag,
            invoice_enabled_flag,
            costing_enabled_flag,
            orderable_on_web_flag,
            cost_of_sales_account,
            sales_account,
            (SELECT AR_NAME  FROM INVENTORY.CHART_OF_ACCOUNTS C WHERE C.CHART_OF_ACCOUNTS_ID = I.sales_account) CHART_OF_ACCOUNTS_AR_NAME,
            (SELECT EN_NAME  FROM INVENTORY.CHART_OF_ACCOUNTS C WHERE C.CHART_OF_ACCOUNTS_ID = I.sales_account) CHART_OF_ACCOUNTS_EN_NAME,
            expense_account,
            encumbrance_account,
            acceptable_rate_increase,
            acceptable_rate_decrease,
            order_cost,
            minimum_order_quantity,
            fixed_order_quantity,
            fixed_days_supply,
            maximum_order_quantity,
            vendor_warranty_flag,
            preventive_maintenance_flag,
            warranty_vendor_id,
            max_warranty_amount,
            outside_operation_flag,
            vehicle_item_flag,
            electronic_flag,
            asset_category_id,
            created_by,
            creation_date,
            deleted
          FROM
            items_details I
              WHERE deleted = 0`,
    returns: [],
    bindings: [],
    qstring: "",
    requireCommit: false
  },

  getoneitemDetails:{
      statement:`
          SELECT
            items_id,
            (SELECT AR_NAME  FROM INVENTORY.ITEMS M WHERE M.ITEMS_ID = I.ITEMS_ID) ITEM_AR_NAME,
            (SELECT EN_NAME  FROM INVENTORY.ITEMS M WHERE M.ITEMS_ID = I.ITEMS_ID) ITEM_EN_NAME,
            shippable_enabled_flag,
            purchasing_enabled_flag,
            customer_order_enabled_flag,
            internal_order_enabled_flag,
            invoiceable_item_flag,
            returnable_flag,
            inspection_required_flag,
            receipt_required_flag,
            rfq_required_flag,
            allow_substitute_receipts_flag,
            allow_unordered_receipts_flag,
            allow_express_delivery_flag,
            invoice_enabled_flag,
            costing_enabled_flag,
            orderable_on_web_flag,
            cost_of_sales_account,
            sales_account,
            (SELECT AR_NAME  FROM INVENTORY.CHART_OF_ACCOUNTS C WHERE C.CHART_OF_ACCOUNTS_ID = I.sales_account) CHART_OF_ACCOUNTS_AR_NAME,
            (SELECT EN_NAME  FROM INVENTORY.CHART_OF_ACCOUNTS C WHERE C.CHART_OF_ACCOUNTS_ID = I.sales_account) CHART_OF_ACCOUNTS_EN_NAME,
            expense_account,
            encumbrance_account,
            acceptable_rate_increase,
            acceptable_rate_decrease,
            order_cost,
            minimum_order_quantity,
            fixed_order_quantity,
            fixed_days_supply,
            maximum_order_quantity,
            vendor_warranty_flag,
            preventive_maintenance_flag,
            warranty_vendor_id,
            max_warranty_amount,
            outside_operation_flag,
            vehicle_item_flag,
            electronic_flag,
            asset_category_id,
            created_by,
            creation_date,
            deleted
          FROM
            items_details I
         WHERE items_id=:ITEMS_ID AND deleted = 0`,
          bindings: [],
          qstring: "",
          requireCommit: false
      },
      insertnewitemDetails: {
          statement: `
          INSERT INTO items_details (
                  items_id,
                  shippable_enabled_flag,
                  purchasing_enabled_flag,
                  customer_order_enabled_flag,
                  internal_order_enabled_flag,
                  invoiceable_item_flag,
                  returnable_flag,
                  inspection_required_flag,
                  receipt_required_flag,
                  rfq_required_flag,
                  allow_substitute_receipts_flag,
                  allow_unordered_receipts_flag,
                  allow_express_delivery_flag,
                  invoice_enabled_flag,
                  costing_enabled_flag,
                  orderable_on_web_flag,
                  cost_of_sales_account,
                  sales_account,
                  expense_account,
                  encumbrance_account,
                  acceptable_rate_increase,
                  acceptable_rate_decrease,
                  order_cost,
                  minimum_order_quantity,
                  fixed_order_quantity,
                  fixed_days_supply,
                  maximum_order_quantity,
                  vendor_warranty_flag,
                  preventive_maintenance_flag,
                  warranty_vendor_id,
                  max_warranty_amount,
                  outside_operation_flag,
                  vehicle_item_flag,
                  electronic_flag,
                  asset_category_id
              ) VALUES (
                  :items_id,
                  :shippable_enabled_flag,
                  :purchasing_enabled_flag,
                  :customer_order_enabled_flag,
                  :internal_order_enabled_flag,
                  :invoiceable_item_flag,
                  :returnable_flag,
                  :inspection_required_flag,
                  :receipt_required_flag,
                  :rfq_required_flag,
                  :allow_substitute_receipts_flag,
                  :allow_unordered_receipts_flag,
                  :allow_express_delivery_flag,
                  :invoice_enabled_flag,
                  :costing_enabled_flag,
                  :orderable_on_web_flag,
                  :cost_of_sales_account,
                  :sales_account,
                  :expense_account,
                  :encumbrance_account,
                  :acceptable_rate_increase,
                  :acceptable_rate_decrease,
                  :order_cost,
                  :minimum_order_quantity,
                  :fixed_order_quantity,
                  :fixed_days_supply,
                  :maximum_order_quantity,
                  :vendor_warranty_flag,
                  :preventive_maintenance_flag,
                  :warranty_vendor_id,
                  :max_warranty_amount,
                  :outside_operation_flag,
                  :vehicle_item_flag,
                  :electronic_flag,
                  :asset_category_id
                    )
           RETURN  items_id INTO :R_items_id  `,
          returns: ["R_items_id"],
          bindings: [],
          qstring: "",
          requireCommit: true
      },

      deleteItemsDetails: {
        statement: `UPDATE ITEMS_DETAILS
                      SET DELETED = 1 , DELETED_BY = :DELETED_BY , DELETED_DATE = sysdate
                      WHERE
                          items_id = :ITEMS_ID`,
        returns: [],
        bindings: [],
        qstring: "",
        requireCommit: true
      }
};

module.exports = statements;
