import { Component, OnInit, Input } from '@angular/core';
import { CONSTANTS } from 'src/app/services/constants.service';

@Component({
  selector: 'app-notification-factory',
  templateUrl: './notification-factory.component.html',
  styleUrls: ['./notification-factory.component.scss']
})
export class NotificationFactoryComponent implements OnInit {

  readonly REQ_TYPE = {
    OPEN_BALANCE:CONSTANTS.WORKFLOW.REQUEST_TYPE.INV_OPEN_BALANCE,
    RCV_DOC:CONSTANTS.WORKFLOW.REQUEST_TYPE.RCV_DOCUMENT,
    INV_TRANSFER:CONSTANTS.WORKFLOW.REQUEST_TYPE.INV_TRANSFER,
    CUSTODY_TRANSFER:CONSTANTS.WORKFLOW.REQUEST_TYPE.CUSTODY_TRANSFER,
    CUSTODY_TRANSFER_R:CONSTANTS.WORKFLOW.REQUEST_TYPE.CUSTODY_TRANSFER_R,
    REQ_DOCUMENT:CONSTANTS.WORKFLOW.REQUEST_TYPE.REQ_DOCUMENT,
    JO_REQ_DOCUMENT:CONSTANTS.WORKFLOW.REQUEST_TYPE.JO_REQ_DOCUMENT,
    DISPENCE:CONSTANTS.WORKFLOW.REQUEST_TYPE.DISPENCE,
    RCV_INSPECTION:CONSTANTS.WORKFLOW.REQUEST_TYPE.RCV_INSPECTION,
    RCV_TEMPORARY:CONSTANTS.WORKFLOW.REQUEST_TYPE.RCV_TEMPORARY,
    INV_TRANSFER_R:CONSTANTS.WORKFLOW.REQUEST_TYPE.INV_TRANSFER_R,
    INV_STOCKTAKING:CONSTANTS.WORKFLOW.REQUEST_TYPE.INV_STOCKTAKING,
    ITEM_RETURN_REQUEST:CONSTANTS.WORKFLOW.REQUEST_TYPE.ITEM_RETURN_REQUEST,
    ITEM_LOSE_REQUEST:CONSTANTS.WORKFLOW.REQUEST_TYPE.ITEM_LOSE_REQUEST,
    EMPLOYEE_CUSTODY_REQUEST:CONSTANTS.WORKFLOW.REQUEST_TYPE.EMPLOYEE_CUSTODY_REQUEST,
    ITEM_RECEIVE_REQUEST:CONSTANTS.WORKFLOW.REQUEST_TYPE.ITEM_RECEIVE_REQUEST,
    ITEM_REQUEST:CONSTANTS.WORKFLOW.REQUEST_TYPE.ITEM_REQUEST,
  }

  @Input() notificationData:any;
  constructor() { }

  ngOnInit() {
  }

}
